id: P07A397F8
initial_creation_type: ocr
source_metadata:
  volumes:
    8f35baefe48c4a85984f61d11470924e:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ཆུ་གཏོར་གྱི་ཆོ་ག།
      total_pages: 1464
      volume_number: 47
